#PBS -N nnoptim_0518_real_psf_with_TV_0.1
#PBS -o /gdata/zhoutk/Deconv/nnoptim_0518_real_psf_with_TV_0.1.out
#PBS -e /gdata/zhoutk/Deconv/nnoptim_0518_real_psf_with_TV_0.1.err
#PBS -l nodes=1:gpus=1:S
#PBS -r y
cd $PBS_O_WORKDIR
echo Time is 'date'
echo Directory is $PWD
echo This job rns on following nodes:
cat $PBS_NODEFILE
cat $PBS_GPUFILE
startdocker -D /gdata/zhoutk -P /ghome/zhoutk -s DeconvNet/source/nnoptim.py bit:5000/deepo


